### PR TITLE
Add `inform_on` decorator for python.

### PR DESCRIPTION
**Pull request by zspencer**

### CODE REVIEW

**Comment by zspencer** [comment]
@lynncyrin OK now this is looking more like Real Python. Mind doing a sanity check for me around weirdness?

**Comment by coilysiren** [comment]
@zspencer thoughts

- I don't have any specific suggestions about where it would be effective, but for a package like this I feel there should be strong integration with the [logging](https://docs.python.org/3/library/logging.html) module
- I'm going to want to use `@inform_on(level='info'` as `@inform_on.info(` to mirror the `logger.info` calls I use currently
- I'm not sure about a general python api for settings, but for good django integration you are definitely going to want `FakeInformant` to be defined with a settings value
- putting the last two items together, I would ideally be using this module like

```python
@inform_on.info
def do_something(self, force=False):
```

EDIT: ah oops, that was a bit more thorough than a sanity check ^^

**Comment by dorfsmay** [comment]
Python actually has a really good logging framework, it probably would be easier to use it rather than trying to re-invent it, and you'd get redirect to a file etc... for free:

```
import logging
import time

logging.basicConfig(format='==> %(module)s, %(funcName)s %(message)s', level=logging.ERROR)
# with fancy time
# logging.basicConfig(filename='/tmp/test.log', format='%(asctime)sZ pid:%(process)s module:%(module)s %(message)s', level=logging.ERROR)

logging.info('blah blah')
logging.debug('you won\'t see this')

.../...

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--debug', '-d', action='store_true')

.../...

if args.debug:
    logging.getLogger().setLevel(logging.DEBUG)
```

**Comment by zspencer** [comment]
Yep! The next steps I have are to actually hook into the logging library in the same (or similar) way the Ruby one does.

The goal here is to make it easy to instrument entrances and exits to a function with the surrounding context for debugging purposes and to populate event based analysis systems.

This way instead of people having to decide exactly what message to log they state they want to inform on a given method and include particular context and it sends that.

Next few commits will replace the fake informant with one that delegates to the standard logging library.

**Comment by zspencer** [comment]
@lynncyrin  - Good point on `inform_on.info` I was initially attempting to mirror the design of the ruby DSL, but I could see an `inform_on.info` working there as well, and if it would feel more natural to you I think it's a good suggestion!

**Comment by zspencer** [comment]
@lynncyrin + @dorfsmay - This now integrates tightly with the built in logging module. The `example.py` file demonstrates how to instrument a class.

I've split out a feature request for `@inform_on.info` instead of using `@inform_on(level=...`

**Pull request merged**
